aws:
    version: latest
    region: us-west-1
    scheme: https
    endpoint: https://localstack.mikroe.com
    use_path_style_endpoint: true
    credentials:
        key: "%env(AWS_KEY)%"
        secret: "%env(AWS_SECRET)%"
